apiVersion: v1
kind: Service
metadata:
  name: {{ template "caluma.fullname" . }}-alexandria
  labels:
{{ include "caluma.labels" . | indent 4 }}
    app.kubernetes.io/component: alexandria
spec:
  type: {{ .Values.alexandria.service.type }}
  ports:
    - port: 8000
      targetPort: alexandria
      protocol: TCP
      name: alexandria
  selector:
    app.kubernetes.io/name: {{ include "caluma.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: alexandria
