apiVersion: v1
kind: Service
metadata:
  name: {{ template "caluma.fullname" . }}-emeis
  labels:
{{ include "caluma.labels" . | indent 4 }}
    app.kubernetes.io/component: emeis
spec:
  type: {{ .Values.emeis.service.type }}
  ports:
    - port: 8000
      targetPort: emeis
      protocol: TCP
      name: emeis
  selector:
    app.kubernetes.io/name: {{ include "caluma.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: emeis
